# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.4.0/charts/library/common/values.schema.json
app-template:
  defaultPodOptions:
    automountServiceAccountToken: false
    securityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
      fsGroupChangePolicy: "OnRootMismatch"

  controllers:
    # Configure the main controller
    main:
      type: deployment
      annotations:
        reloader.stakater.com/auto: "true"

      containers:
        # Configure the main application container
        main:
          image:
            repository: ghcr.io/c4illin/convertx
            tag: v0.12.1@sha256:d54b3deb00f990d90ccd18b5340d9ba91da209e5d8ccc670203f5dd342acf672
          env:
            TZ: Europe/Vilnius
          ports:
            - name: http
              containerPort: 3000
          probes:
            liveness:
              enabled: true
              type: HTTP
            readiness:
              enabled: true
              type: HTTP
  service:
    # Configure a service for the main application
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 3000

  ingress:
    # Configure an Ingress for the main application
    main:
      annotations:
        cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
        external-dns.alpha.kubernetes.io/hostname: &host paperless.homelab.net
        external-dns.alpha.kubernetes.io/target: home.homelab.net
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: convertx
        gethomepage.dev/description: Self-hosted online file converter
        gethomepage.dev/group: Tooling
        gethomepage.dev/icon: https://raw.githubusercontent.com/C4illin/ConvertX/main/public/favicon-32x32.png
      className: "traefik"
      hosts:
        - host: *host
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - secretName: convert-tls-secret
          hosts:
            - *host

  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: convertx-data-pvc
      globalMounts:
        - path: /app/data
nfs:
  pv:
    - name: convertx-data
      storage: 1Gi
      path: /Seagate/convertx/data
      server: 192.168.10.41
