apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pihole-admin-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: pihole-admin-password
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: pihole_password
