apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole-tls
  namespace: pihole
spec:
  secretName: pihole-tls-secret
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days before expiration
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  commonName: pihole.homelab.net
  dnsNames:
    - pihole.homelab.net
    - www.pihole.homelab.net
