cert-manager:
  installCRDs: true
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true
  podDnsPolicy: None
  podDnsConfig:
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
  webhook:
    resources:
      requests:
        cpu: 20m
        memory: 32Mi
      limits:
        cpu: 30m
        memory: 100Mi
  resources:
    requests:
      cpu: 20m
      memory: 40Mi
    limits:
      cpu: 45m
      memory: 80Mi
