# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.4.0/charts/library/common/values.schema.json
app-template:
  defaultPodOptions:
    securityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups:
        - 65534
  controllers:
    calibre-web:
      type: statefulset
      strategy: RollingUpdate
      containers:
        app:
          image:
            repository: ghcr.io/bjw-s-labs/calibre-web
            tag: 0.6.24@sha256:bd76e12e6ea54e50f56961aee202e1087dd45ad42de12440501dccae2ab90690
          env:
            CACHE_DIR: /cache
          resources:
            requests:
              cpu: 15m
              memory: 249M
            limits:
              memory: 299M
  service:
    main:
      controller: calibre-web
      ports:
        http:
          port: 8083
  # ingress:
  #   main:
  #     enabled: true
  #     className: external
  #     annotations:
  #       nginx.ingress.kubernetes.io/auth-response-headers:
  #         Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
  #       nginx.ingress.kubernetes.io/auth-snippet:
  #         proxy_set_header X-Forwarded-Host $http_host;
  #       nginx.ingress.kubernetes.io/auth-url:
  #         http://ak-outpost-proxy-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
  #       nginx.ingress.kubernetes.io/auth-signin:
  #         /outpost.goauthentik.io/start?rd=$escaped_request_uri
  #     hosts:
  #       - host: &host calibre-web.${EXTERNAL_DOMAIN}
  #         paths:
  #           - path: /
  #             service:
  #               identifier: main
  #               port: http
  #     tls:
  #       - hosts: [*host]
  ingress:
    main:
      enabled: true
      className: "traefik"
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Calibre Web
        gethomepage.dev/description: E-book manager
        gethomepage.dev/group: Media
        gethomepage.dev/icon: https://raw.githubusercontent.com/kovidgoyal/calibre/master/resources/images/lt.png
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
        external-dns.alpha.kubernetes.io/hostname: &host calibre.homelab.net
        external-dns.alpha.kubernetes.io/target: home.homelab.net
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        ingressClassName: "traefik"
      hosts:
        - host: *host
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - secretName: tools-tls-secret
          hosts:
            - *host
  persistence:
    config:
      enabled: true
      type: nfs
      server: 192.168.10.41
      path: /Seagate/calibre/config
      globalMounts:
        - path: /config
    media:
      enabled: true
      type: nfs
      server: 192.168.10.41
      path: /Seagate/calibre/media
      globalMounts:
        - path: /data/media
    cache:
      enabled: true
      type: emptyDir
      globalMounts:
        - path: /cache
