external-dns:
  provider: pihole
  # IMPORTANT: If you have records that you manage manually in Pi-hole, set
  # the policy to upsert-only so they do not get deleted.
  policy: upsert-only
  # Pihole only supports A/AAAA/CNAME records so there is no mechanism to track ownership.
  # You don't need to set this flag, but if you leave it unset, you will receive warning
  # logs when ExternalDNS attempts to create TXT records.
  registry: noop
  pihole:
    server: http://pihole-web.pihole.svc.cluster.local
    secretName: pihole-admin-password
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  annotationFilter: external-dns.alpha.kubernetes.io/exclude notin (true)
