apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gitlab-secret-store
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5" # Runs after CRDs (weight=0)
spec:
  provider:
    gitlab:
      auth:
        SecretRef:
          accessToken:
            name: gitlab-secret
            namespace: external-secrets
            key: token
      projectID: "68897114"

