apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-secret-store
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-secret-store
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-secret-store
subjects:
  - kind: ServiceAccount
    name: k8s-secret-store
    namespace: external-secrets
roleRef:
  kind: ClusterRole
  name: k8s-secret-store
  apiGroup: rbac.authorization.k8s.io

