apiVersion: v2
name: metrics-server
description: Scalable and efficient source of container resource metrics for Kubernetes built-in autoscaling pipelines
type: application
version: 0.1.0
dependencies:
  - name: metrics-server
    repository: https://kubernetes-sigs.github.io/metrics-server
    version: 3.12.2
