metrics-server:
  hostNetwork: 
    enabled: false
  replicas: 1
  args:
    - --kubelet-preferred-address-types=InternalIP,Hostname
    - --kubelet-insecure-tls
  rbac:
    create: true
  apiService:
    create: true