loki:
  deploymentMode: SingleBinary
  persistence:
    enabled: true
    storageClass: "" # explicitly empty since you're using static PV
    accessModes:
      - ReadWriteMany
    size: 5Gi
    existingClaim: loki-folder-pvc
  loki:
    auth_enabled: false
    compactor:
      retention_enabled: true
      delete_request_store: filesystem
    ingester:
      chunk_encoding: snappy
    limits_config:
      retention_period: 7d
      allow_structured_metadata: true
    commonConfig:
      replication_factor: 1
    tracing:
      enabled: true
    storage:
      type: "filesystem"
    schemaConfig:
      configs:
        - from: "2024-01-01"
          store: tsdb
          index:
            prefix: loki_index_
            period: 24h
          object_store: filesystem
          schema: v13
    querier:
      # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
      max_concurrent: 2
  resultsCache:
    # -- Specifies whether memcached based results-cache should be enabled
    enabled: false
  memcachedExporter:
    # -- Whether memcached metrics should be exported
    enabled: false
  chunksCache:
    enabled: false
    writebackSizeLimit: 100MB
  gateway:
    service:
      labels:
        prometheus.io/service-monitor: "false"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: []
  monitoring:
    serviceMonitor:
      enabled: true
    rules:
      enabled: true
  singleBinary:
    replicas: 1
    resoures:
      limits:
        cpu: 10m
        memory: 50Mi
      requests:
        cpu: 20m
        memory: 100Mi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: []

  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0

  ingester:
    replicas: 0
  querier:
    replicas: 0
  queryFrontend:
    replicas: 0
  queryScheduler:
    replicas: 0
  distributor:
    replicas: 0
  compactor:
    replicas: 0
  indexGateway:
    replicas: 0
  bloomCompactor:
    replicas: 0
  bloomGateway:
    replicas: 0

nfs:
  pv:
    - name: loki-folder
      storage: 5Gi
      path: /Seagate/loki
      server: 192.168.10.41