pihole:
  ingress:
    enabled: true
    hosts:
      - pihole.homelab.net
    path: /
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
      external-dns.alpha.kubernetes.io/hostname: pihole.homelab.net
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    tls:
      - secretName: pihole-tls-secret
        hosts:
          - pihole.homelab.net
  #  - secretName: chart-example-tls
  #    hosts:
  #     #- virtualHost (default value is pi.hole) will be appended to the hosts
  #      - chart-example.local

  persistentVolumeClaim:
    enabled: false

  dnsmasq:
    customDnsEntries:
      - "address=/cloud.lan/192.168.10.100"
      - "address=/pihole.cloud.lan/192.168.10.100"
      - "address=/rancher.cloud.lan/192.168.10.100"
      - "address=/grafana.cloud.lan/192.168.10.100"
      - "address=/traefik-dashboard.cloud.lan/192.168.10.100"
      - "address=/calibre.cloud.lan/192.168.10.100"
      - "address=/pihole.homelab.net/10.101.0.211"
      - "address=/plex.cloud.lan/192.168.10.100"
    customSettings:
      # permit all origins
      - except-interface=nonexisting

  serviceWeb:
    type: ClusterIP

  serviceDns:
    loadBalancerIP: 192.168.10.101
    externalTrafficPolicy: Cluster
    annotations:
      metallb.universe.tf/allow-shared-ip: pihole-svc
    type: LoadBalancer

  podDnsConfig:
    enabled: true
    policy: "None"
    nameservers:
      - "127.0.0.1"
      - "1.1.1.1"
      - "1.0.0.1"
  admin:
    enabled: true
    existingSecret: pihole-admin-password
    passwordKey: admin-password

  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 50Mi

  extraEnvVars:
    DNSMASQ_USER: "root"

  env:
    TZ: Europe/Vilnius
    FTLCONF_LOCAL_IPV4: 192.168.10.101
    DNSMASQ_LISTENING: "all"
    FTLCONF_RATE_LIMIT: "0/0"
